//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrenregistratieService
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class Task
    {
        public int Taskid { get; set; }
        public int Hours { get; set; }
        public string Name { get; set; }

        public virtual AppUser AppUser { get; set; }
    }
}
